# Generated by Django 5.2.12 on 2026-04-05 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_abusereport_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abusereport',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_about_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserModerationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_reports_count', models.PositiveIntegerField(default=0)),
                ('is_under_moderation', models.BooleanField(default=False)),
                ('hidden_from_swipe_until', models.DateTimeField(blank=True, null=True)),
                ('last_reason', models.CharField(blank=True, max_length=220)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation status',
                'verbose_name_plural': 'Moderation statuses',
            },
        ),
    ]

