# Generated by Django 5.2.12 on 2026-04-05 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_emailverification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usermoderationstatus',
            options={'verbose_name': 'Статус модерации', 'verbose_name_plural': 'Статусы модерации'},
        ),
        migrations.CreateModel(
            name='ModerationAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('reviewed', 'Рассмотрена'), ('rejected', 'Отклонена')], default='open', max_length=16)),
                ('moderator_note', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_appeals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
