# Generated by Django 5.2.12 on 2026-04-05 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_emailverification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user', '-created_at'], name='core_match_user_id_19cfda_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['pet', '-created_at'], name='core_match_pet_id_fcbe2e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['match', 'created_at'], name='core_messag_match_i_f4a1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='core_messag_sender__43db24_idx'),
        ),
        migrations.AddIndex(
            model_name='swipe',
            index=models.Index(fields=['user', 'created_at'], name='core_swipe_user_id_fbdc26_idx'),
        ),
        migrations.AddIndex(
            model_name='swipe',
            index=models.Index(fields=['pet', 'created_at'], name='core_swipe_pet_id_d0dbb5_idx'),
        ),
    ]
